// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StudyTideForge.Data.Migrations;

[DbContext(typeof(ForgeDbContext))]
public sealed class ForgeDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

        modelBuilder.Entity("StudyTideForge.Models.Flashcard", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Answer")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("Difficulty")
                    .HasColumnType("INTEGER");

                b.Property<int>("LessonId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Question")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("TimesCorrect")
                    .HasColumnType("INTEGER");

                b.Property<int>("TimesIncorrect")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("LessonId");

                b.ToTable("Flashcards");
            });

        modelBuilder.Entity("StudyTideForge.Models.PracticeAttempt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<double>("AccuracyPercent")
                    .HasColumnType("REAL");

                b.Property<DateTime>("AttemptedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("ErrorCount")
                    .HasColumnType("INTEGER");

                b.Property<int>("FirstMismatchIndex")
                    .HasColumnType("INTEGER");

                b.Property<int>("TrainingBlockId")
                    .HasColumnType("INTEGER");

                b.Property<string>("TypedText")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AttemptedAt");

                b.HasIndex("TrainingBlockId");

                b.ToTable("PracticeAttempts");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingBlock", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Difficulty")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("LastPracticedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("LessonId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("NextDueAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int>("TimesPerfect")
                    .HasColumnType("INTEGER");

                b.Property<int>("TimesPracticed")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("LessonId");

                b.HasIndex("NextDueAt");

                b.ToTable("TrainingBlocks");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingLesson", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("ModuleId")
                    .HasColumnType("INTEGER");

                b.Property<int>("OrderIndex")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ModuleId", "OrderIndex");

                b.ToTable("TrainingLessons");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingModule", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Category", "Name")
                    .IsUnique();

                b.ToTable("TrainingModules");
            });

        modelBuilder.Entity("StudyTideForge.Models.Flashcard", b =>
            {
                b.HasOne("StudyTideForge.Models.TrainingLesson", "Lesson")
                    .WithMany("Flashcards")
                    .HasForeignKey("LessonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Lesson");
            });

        modelBuilder.Entity("StudyTideForge.Models.PracticeAttempt", b =>
            {
                b.HasOne("StudyTideForge.Models.TrainingBlock", "TrainingBlock")
                    .WithMany("PracticeAttempts")
                    .HasForeignKey("TrainingBlockId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("TrainingBlock");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingBlock", b =>
            {
                b.HasOne("StudyTideForge.Models.TrainingLesson", "Lesson")
                    .WithMany("TrainingBlocks")
                    .HasForeignKey("LessonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Lesson");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingLesson", b =>
            {
                b.HasOne("StudyTideForge.Models.TrainingModule", "Module")
                    .WithMany("Lessons")
                    .HasForeignKey("ModuleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Module");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingBlock", b =>
            {
                b.Navigation("PracticeAttempts");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingLesson", b =>
            {
                b.Navigation("Flashcards");

                b.Navigation("TrainingBlocks");
            });

        modelBuilder.Entity("StudyTideForge.Models.TrainingModule", b =>
            {
                b.Navigation("Lessons");
            });
#pragma warning restore 612, 618
    }
}
