// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyTideTrainer.Data;

#nullable disable

namespace StudyTideTrainer.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    partial class TrainingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("StudyTideTrainer.Models.PracticeAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccuracyPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraChars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstMismatchIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingChars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnippetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("SnippetId");

                    b.ToTable("PracticeAttempts");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.Snippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerfect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesPracticed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextDueAt");

                    b.HasIndex("TopicId");

                    b.ToTable("Snippets");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.PracticeAttempt", b =>
                {
                    b.HasOne("StudyTideTrainer.Models.Snippet", "Snippet")
                        .WithMany("PracticeAttempts")
                        .HasForeignKey("SnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snippet");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.Snippet", b =>
                {
                    b.HasOne("StudyTideTrainer.Models.Topic", "Topic")
                        .WithMany("Snippets")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.Snippet", b =>
                {
                    b.Navigation("PracticeAttempts");
                });

            modelBuilder.Entity("StudyTideTrainer.Models.Topic", b =>
                {
                    b.Navigation("Snippets");
                });
#pragma warning restore 612, 618
        }
    }
}
